import Footer from "@/shared/components/Footer";
import { NavBar } from "@/shared/components/NavBar";
import "@/shared/styles/globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang={"en"}>
			<body
				className={
					"bg-background dark:bg-background-dark text-on-background dark:text-on-background-dark h-screen font-sans overflow-clip"
				}
			>
				{children}
			</body>
		</html>
	);
}
