import "@/shared/styles/globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang={"en"}>
			<body
				className={
					"bg-background dark:bg-background-dark text-on-background dark:text-on-background-dark h-screen font-sans overflow-clip"
				}
			>
				<Toaster
					toastOptions={{
						className:
							"bg-background-100! dark:bg-background-dark-100! text-on-background! dark:text-on-background-dark! border-2 dark:border-white",
					}}
				></Toaster>
				{children}
			</body>
		</html>
	);
}
