import Footer from "@/components/Footer/Footer";
import { NavBar } from "@/components/NavBar/NavBar";
import { openSans } from "@/fonts/fonts";
import "@/styles/globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang={"en"}>
      <body className={"bg-background dark:bg-background-dark flex flex-col h-screen font-sans"}>
        <NavBar />
        <main className={"flex-1 overflow-y-auto p-4"}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
