import "@/shared/styles/globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <main>{children}</main>;
}
