import { NavBar } from "@/shared/components/NavBar";
import "@/shared/styles/globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<main>
			<NavBar type={"auth"}></NavBar>
			<div className="max-w-[800px] mx-auto">{children}</div>
		</main>
	);
}
