export const ROUTES = [
  { name: "Inicio", path: "/" },
  { name: "Mi perfil", path: "/miPerfil" },
  { name: "Editar perfil", path: "/editarPerfil" },
  { name: "Borrar perfil", path: "/borrarPerfil" },
  { name: "Cuenta borrada", path: "/perfilBorrado" },
  { name: "Cambiar contraseña", path: "/cambiarContrasena" },
  { name: "Sign up", path: "/signUp" },
  { name: "Login", path: "/login" },
  { name: "Crear perfil", path: "/crearPerfil" },
  { name: "Eliminar amigo", path: "/:id//eliminarAmigo" },
  { name: "Añadir persona", path: "/anadirPersona" },
  { name: "Amigos", path: "/amigos" },
  { name: "Añadir a grupo", path: "/:id/anadirGrupo" },
  { name: "Regalos", path: "/regalos" },
  { name: "Nuevo regalo", path: "/nuevoRegalo" },
  { name: "Nuevo regalo amigo", path: "/:id/nuevoRegaloAmigo" },
  { name: "Editar regalo", path: "/regalos/:id/editarRegalo" },
  { name: "Perfil", path: "/:id" },
  { name: "Grupos", path: "/listaGrupos" },
  { name: "Grupo", path: "/grupo/:id" },
  { name: "Crear grupo", path: "/crearGrupo" },
  { name: "Editar grupo", path: "/grupo/:id/editarGrupo" },
  { name: "Añadir persona a grupo", path: "/grupo/:id/anadirPersonaGrupo" },
  { name: "Añadir evento", path: "/grupo/:id/crearEvento" },
  { name: "Dejar grupo", path: "/grupo/:id/salirGrupo" },
  { name: "Borrar grupo", path: "/grupo/:id/borrarGrupo" },
  { name: "Evento", path: "/evento/:id" },
  { name: "Editar evento", path: "/evento/:id/editarEvento" },
  { name: "Borrar evento", path: "/evento/:id/borrarEvento" },
  { name: "Crear amigo invisible", path: "/evento/:id/crearAmigoInvisible" },
  { name: "Ayuda", path: "/ayuda" },
  { name: "Contraseña olvidada", path: "/contrasenaOlvidada" },
  { name: "Restablecer contraseña", path: "/restablecerContrasena" },
  { name: "Mensajes", path: "/mensajes" },
]