export const ROUTES = [
	{ name: "Home", path: "/" },
	{ name: "Profile", path: "/profile" },
	{ name: "Profile settings", path: "/profile-settings" },
	{ name: "Delete account", path: "/delete-account" },
	{ name: "Account deleted", path: "/account-deleted" },
	{ name: "Sign up", path: "/sign-up" },
	{ name: "Login", path: "/login" },
	{ name: "New profile", path: "/new-profile" },
	{ name: "Remove friend", path: "/:id/remove-friend" },
	{ name: "Add person", path: "/add-person" },
	{ name: "Friends", path: "/friends" },
	{ name: "Friend profile", path: "/friends/:id" },
	{ name: "New gift for friend", path: "/friends/:id/new-gift-for-friend" },
	{ name: "Add to group", path: "/:id/add-to-group" },
	{ name: "Gifts", path: "/gifts" },
	{ name: "New gift", path: "/gifts/new" },
	{ name: "Edit gift", path: "/gifts/:id/edit" },
	{ name: "Friend profile", path: "/:id" },
	{ name: "Groups", path: "/groups" },
	{ name: "Group", path: "/group/:id" },
	{ name: "Create group", path: "/create-group" },
	{ name: "Edit group", path: "/group/:id/edit-group" },
	{ name: "Add person to group", path: "/group/:id/add-person-to-group" },
	{ name: "Create event", path: "/group/:id/create-event" },
	{ name: "Leave group", path: "/group/:id/leave-group" },
	{ name: "Delete group", path: "/group/:id/delete-group" },
	{ name: "Event", path: "/event/:id" },
	{ name: "Edit event", path: "/event/:id/edit-event" },
	{ name: "Delete event", path: "/event/:id/delete-event" },
	{ name: "Create secret friend", path: "/event/:id/create-secret-friend" },
	{ name: "Help", path: "/help" },
	{ name: "Forgot password", path: "/forgot-password" },
	{ name: "Reset password", path: "/reset-password" },
	{ name: "Messages", path: "/messages" },
];
