export const ROUTES = [
	{ name: "Home", path: "/" },
	{ name: "Profile", path: "/profile" },
	{ name: "Profile settings", path: "/profile-settings" },
	{ name: "Delete account", path: "/delete-account" },
	{ name: "Account deleted", path: "/account-deleted" },
	{ name: "Sign up", path: "/sign-up" },
	{ name: "Login", path: "/login" },
	{ name: "New profile", path: "/new-profile" },
	{ name: "Remove friend", path: "/:id/remove-friend" },
	{ name: "Add person", path: "/add-person" },
	{ name: "Friends", path: "/friends" },
	{ name: "Friend profile", path: "/friends/:id" },
	{ name: "New gift for friend", path: "/friends/:id/new-gift-for-friend" },
	{ name: "Gifts", path: "/gifts" },
	{ name: "New gift", path: "/gifts/new" },
	{ name: "Edit gift", path: "/gifts/:id/edit" },
	{ name: "Calendar", path: "/calendar" },
	{ name: "New event", path: "/calendar/new-event" },
	{ name: "Event", path: "/calendar/:id" },
	{ name: "Edit event", path: "/calendar/:id/edit-event" },
	{ name: "Delete event", path: "/calendar/:id/delete-event" },
	{ name: "Create secret friend", path: "/calendar/:id/create-secret-friend" },
	{ name: "Help", path: "/help" },
	{ name: "Forgot password", path: "/forgot-password" },
	{ name: "Reset password", path: "/reset-password" },
	{ name: "Messages", path: "/messages" },
];
